// src/App.tsx
import Navbar from './components/Navbar';
import RecommendMenu from './components/RecommendMenu';
import FindRestaurants from './components/FindRestaurants';

export default function App() {
  return (
    <>
      <Navbar />
      <RecommendMenu reason="비오니까" menu="돼지국밥" />
      <FindRestaurants menu="돼지국밥" />
    </>
  );
}

// src/App.svelte
<script lang="ts">
    import Layout from "./lib/Layout.svelte";
    import Recommend from "./lib/Recommend.svelte";
    import Map from "./lib/Map.svelte";

    const mealtime: string = "점심";
    const reason: string = "비오니까";
    const menu: string = "돼지국밥";
</script>

<Layout>
    <main>
        <Recommend mealtime={mealtime} reason={reason} menu={menu} />
        <Map menu={menu} />
    </main>
</Layout>
